### ISSUE TITLE
GUI containing pane masks with excessive size can wipe player's inventory

### ISSUE THREAD

**Issue by SamB440** [stefvanschie/IF#125]
When creating a ChestGUI that has panes with masks in them, if the height of the pane combined with a mask causes it to go outside the chest GUI, it will enter the player's inventory and result in their inventory being wiped. (sometimes some items are returned - but nearly always armour etc is wiped)
Example of this happening:
![image](https://user-images.githubusercontent.com/11319274/127385755-d6283883-694b-4b42-a60c-bd0d4b6cf36c.png)

This occurred with the following configuration in my plugin, where the rows of the gui is set to 5 yet the pane height and mask goes outside it:
```
    gui:
      default_region_icon: TOTEM_OF_UNDYING
      general:
        rows: 5
      back:
        posX: 0
        posY: 5
        length: 1
        height: 1
        back: ARROW
      forward:
        posX: 8
        posY: 5
        length: 1
        height: 1
        forward: ARROW
      exit:
        posX: 4
        posY: 5
        length: 1
        height: 1
        command: ''
        show: true
        exit: BARRIER
      pane:
        posX: 1
        posY: 1
        length: 7
        height: 4
      outlinePane:
        posX: 0
        posY: 0
        length: 9
        height: 6
        show: true
        mask:
        - '111111111'
        - '100000001'
        - '100000001'
        - '100000001'
        - '100000001'
        - '111111111'
        outlinePane: GRAY_STAINED_GLASS_PANE
      innerPane:
        posX: 1
        posY: 1
        length: 7
        height: 4
        show: true
        mask:
        - '1111111'
        - '1111111'
        - '1111111'
        - '1111111'
        innerPane: WHITE_STAINED_GLASS_PANE
```

Code for creation of the gui:
`new ChestGui(plugin.getConfig().getInt("settings.server.gui.general.rows"), Translations.REGIONS.get(player));`

Full code here, but rather a pain to look through: https://gitlab.com/SamB440/rpgregions-2/-/blob/master/rpgregions/src/main/java/net/islandearth/rpgregions/gui/DiscoveryGUI.java

## Version
IF: 0.10.0
Server: 
```
This server is running Paper version git-Paper-136 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7480b94)
You are running the latest version
Previous version: git-Paper-119 (MC: 1.17.1)
```
